version: '2'
services:
  web:
    image: poonlap/odoo-th:latest # latest == 14.0
    command: -- --dev=all
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo-web:/var/lib/odoo 
      # ./data:/var/lib/odoo # You need to change the permission of data folder to be writable by docker deamone.
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
  pg4:
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8072:80'
    environment:
      PGADMIN_DEFAULT_EMAIL : 'admindb@gmail.com'
      PGADMIN_DEFAULT_PASSWORD : 'admindbpass'

volumes:
  odoo-db-data:
  odoo-web:
